// Review-only palettes. Selecting one here does not change saved projects or defaults.
export const colorOptions=[
 {id:'navy',name:'네이비 · 소프트 골드',description:'옅은 블루그레이 바탕 · 차분한 네이비',colors:{paper:'#edf0f5',wash:'#e2e7ee',line:'#cdd5df',ink:'#222a34',muted:'#59616d',accent:'#182b49',title:'#182b49',detail:'#af8e4d',hero:'#182b49','hero-title':'#e4d4b4'}},
 {id:'teal',name:'딥틸 · 아이스블루',description:'아이스블루 바탕 · 딥틸과 라이트골드',selected:true,colors:{paper:'#e7f1f2',wash:'#d7e8eb',line:'#c4d9dd',ink:'#263a3d',muted:'#53666a',accent:'#15616d',title:'#174650',detail:'#45818b',hero:'#15616d','hero-title':'#f3dda6'}},
 {id:'wine',name:'와인 · 펄그레이',description:'펄그레이 바탕 · 깊은 와인색',colors:{paper:'#f0ebed',wash:'#e7dfe3',line:'#d8cdd2',ink:'#30282b',muted:'#65585d',accent:'#651c32',title:'#651c32',detail:'#946776',hero:'#651c32','hero-title':'#f4f4f4'}}
];

export function buildColorOptions(previewUrl='color.html'){
 const initial=colorOptions.findIndex(option=>option.selected);
 const buttons=colorOptions.map((option,i)=>`<button type="button" class="palette" data-palette="${option.id}" aria-pressed="${i===initial}" style="--band:${option.colors.hero};--name:${option.colors['hero-title']};--paper:${option.colors.paper}"><span class="palette-picture" aria-hidden="true"><span>Eunnyeong Heo</span></span><span class="palette-label"><span class="palette-number">0${i+1}</span><strong>${option.name}</strong>${option.selected?'<span class="recommended">선택한 조합</span>':''}</span><span class="palette-description">${option.description}</span></button>`).join('');
 return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>컬러형 · 색상 비교</title><link rel="icon" href="../favicon.svg" type="image/svg+xml"><style>
@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-dynamic-subset.min.css');
*{box-sizing:border-box}body{margin:0;background:#f4f5f6;color:#252b30;font:14px/1.6 Pretendard,sans-serif}main{max-width:1360px;margin:auto;padding:32px 32px 48px}header{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:22px}.eyebrow{font-size:12px;color:#78828a}h1{font-size:27px;letter-spacing:-.9px;line-height:1.3;margin:5px 0 7px}header p{margin:0;color:#66717a;word-break:keep-all}header a{color:#55636e;text-decoration:none;font-size:13px;white-space:nowrap}header a:hover{text-decoration:underline}.palettes{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px;margin-bottom:24px}.palette{display:block;text-align:left;border:1px solid #dce0e3;background:#fff;border-radius:8px;padding:8px;cursor:pointer;min-width:0;color:inherit;font:inherit;transition:border-color .15s,box-shadow .15s}.palette[aria-pressed=true]{border-color:#293743;box-shadow:0 0 0 1px #293743}.palette-picture{display:flex;align-items:center;min-height:75px;background:var(--band);border-top:12px solid var(--paper);padding:14px 18px;border-radius:3px;color:var(--name);font:500 26px/1.2 Georgia,serif;letter-spacing:-.6px}.palette-label{display:flex;align-items:center;gap:8px;padding:11px 8px 2px;flex-wrap:wrap}.palette-number{color:#859099;font-size:11px}.palette-label strong{font-size:14px;font-weight:600}.recommended{font-size:10px;padding:1px 5px;border-radius:3px;background:#eef1f3;color:#465460}.palette-description{display:block;color:#6d7880;font-size:12px;padding:0 8px 6px;word-break:keep-all}.preview-bar{display:flex;align-items:center;justify-content:space-between;gap:16px;font-size:12px;color:#65717b;margin-bottom:10px}.preview-bar strong{color:#3c4852;font-weight:500}.devices{display:flex;gap:4px}.devices button{border:0;background:transparent;color:#67737c;font:inherit;padding:5px 10px;border-radius:4px;cursor:pointer}.devices button[aria-pressed=true]{background:#e2e6e9;color:#27343e}.preview-frame{border:1px solid #dde2e5;border-radius:7px;overflow:hidden;background:#e7ebee;display:flex;justify-content:center;align-items:start;padding:0}.preview-frame[data-mobile=true]{padding:24px 0}iframe{display:block;width:100%;height:760px;border:0;background:white}.preview-frame[data-mobile=true] iframe{width:390px;max-width:100%;height:780px;box-shadow:0 8px 30px #23313c15}.note{font-size:12px;color:#7c858d;margin:12px 0 0}button:focus-visible,a:focus-visible{outline:2px solid #263848;outline-offset:4px}@media(max-width:700px){main{padding:22px 16px}header{align-items:start}h1{font-size:24px}.palettes{gap:9px}.palette{padding:5px}.palette-picture{min-height:60px;padding:10px;font-size:19px}.palette-label{padding:8px 4px 3px;gap:4px}.palette-label strong{font-size:12px}.palette-description{display:none}.recommended{display:none}.preview-bar{align-items:center}iframe{height:730px}}@media(max-width:430px){.palette-picture{font-size:16px}.palette-number{display:none}.palette-label strong{font-size:11px}}
</style></head><body><main><header><div><span class="eyebrow">03 컬러형</span><h1>어떤 색이 어울릴까요?</h1><p>같은 구성과 사진에 세 가지 색 조합을 입혔어요.</p></div><a href="./">템플릿 목록 ↗</a></header><section class="palettes" aria-label="색상 조합">${buttons}</section><div class="preview-bar"><strong id="preview-label" aria-live="polite">0${initial+1} · ${colorOptions[initial].name}</strong><div class="devices" aria-label="화면 크기"><button type="button" data-device="desktop" aria-pressed="true">PC</button><button type="button" data-device="mobile" aria-pressed="false">모바일</button></div></div><div class="preview-frame"><iframe id="preview" title="허은녕 교수님 컬러형 색상 미리보기"></iframe></div><p class="note">색상을 누르면 미리보기가 바뀝니다. 페이지 안에서 스크롤과 메뉴도 확인할 수 있어요.</p></main><script>
const palettes=${JSON.stringify(colorOptions)},frame=document.getElementById('preview');let selected=palettes[${initial}];
function applyPalette(){const doc=frame.contentDocument;if(!doc?.querySelector('.faculty-site'))return;doc.body.style.setProperty('--public-paper',selected.colors.paper);doc.querySelectorAll('.faculty-site').forEach(site=>{for(const [key,value] of Object.entries(selected.colors))site.style.setProperty('--site-'+key,value)});if(!doc.getElementById('palette-review-style')){const style=doc.createElement('style');style.id='palette-review-style';style.textContent='.site-color-affiliation .site-color-position,.faculty-site[data-template=color] .site-section[data-kind=contact] .site-copy{color:#e7edef}';doc.head.append(style)}}
document.querySelectorAll('[data-palette]').forEach(button=>button.addEventListener('click',()=>{selected=palettes.find(p=>p.id===button.dataset.palette);document.querySelectorAll('[data-palette]').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));document.getElementById('preview-label').textContent='0'+(palettes.indexOf(selected)+1)+' · '+selected.name;applyPalette()}));
document.querySelectorAll('[data-device]').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.preview-frame').dataset.mobile=String(button.dataset.device==='mobile');document.querySelectorAll('[data-device]').forEach(item=>item.setAttribute('aria-pressed',String(item===button)))}));
frame.addEventListener('load',applyPalette);frame.src=${JSON.stringify(previewUrl)};
</script></body></html>`;
}
